import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HomeSpanish from "../content/español/home.json";
import HomeEnglish from "../content/english/home.json";
import { useRouter } from "next/router";

import Header from "../components/Header";
import Footer from "../components/Footer";

const Home: NextPage = () => {
    let { locale } = useRouter();
    let data = locale === "es" ? HomeSpanish : HomeEnglish;


    return (
      <>
            <Head>
                <title>Alejandro Suarez</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header language={locale || "es"} />
      
            <main>
                <section className="hero" id="home">
                    <div className="hero__content">
                        <img src={data.section1.image} alt={data.section1.h1} />
                        <h1>{data.section1.h1}</h1>
                        <h2>
                            {data.section1.h2.start}
                            <span>{data.section1.h2.middleStart}</span>
                            {data.section1.h2.middleEnd}
                            <span>{data.section1.h2.end}</span>.
                            
                        </h2>
                        <button className="button__hero">
                            {data.section1.button.title}
                        </button>
                    </div>
                </section>

                <section className="projects" id="projects">
                    {data.section2.projects.map((project, index) => (
                        <article key={index}>
                            <div>
                                <img src={project.image} alt={project.title} />
                            </div>
                            <div>
                                <h4>{project.thematic}</h4>
                                <h2>{project.title}</h2>
                                <p>{project.subtitle}</p>
                                <div className="btn__container">
                                    <button className="button__projects">
                                        Ver Más
                                    </button>
                                </div>
                            </div>
                        </article>
                    ))}
                </section>

                <section className="tech" >
                  
                  <div className="tech__image"></div>

                  <div className="tech__content" id="technologies">
                    {
                      data.section3.tech.map((tech, index)=> (
                        <div key={index} className="tech__content--block">
                          <h2 className="tech__content--block__title">{tech.title}</h2>
                          <div className="tech__content--block__grid">
                          {
                            tech.images.map((photo, i)=> (
                              <div key={i}>
                                <Image 
                                  src={photo.image} 
                                  alt={photo.name} 
                                  layout="fill"
                                />
                              </div>
                            ))
                          }
                          </div>
                        </div>
                      ))
                    }
                  </div>
                </section>
            </main>
            <Footer />
        </>
    );
};

export default Home;
