import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import HomeSpanish from "../content/español/home.json";
import HomeEnglish from "../content/english/home.json";
import { useRouter } from "next/router";

import Header from "../components/Header";
import Footer from "../components/Footer";

import ProjectsBtn from "../components/ProjectsBtn";
import SourceCodeLinks from "../components/SourceCodeLinks";
import ButtonCv from "../components/ButtonCv";

interface HomeProps{
  data: any,
  locale: string
}


const Home: NextPage<HomeProps> = ({data, locale}) => {
    


    return (
      <>
            <Head>
                <title>Alejandro Suarez</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header language={ locale } />
      
            <main>
                <section className="hero" id="home">
                    <div className="hero__content">
                        <img src={data.section1.image} alt={data.section1.h1} />
                        <h1>{data.section1.h1}</h1>
                        <h2>
                            {data.section1.h2.start}
                            <span>{data.section1.h2.middleStart}</span>
                            {data.section1.h2.middleEnd}
                            <span>{data.section1.h2.end}</span>.
                            
                        </h2>
                        <ButtonCv button={data.section1.button}/>
                    </div>
                </section>

                <section className="projects" id="projects">
                    {data.section2.projects.map((project:any, index:number) => (
                        <article key={index}>
                            <div>
                                <img src={project.image} alt={project.title} />
                            </div>
                            <div>
                                <h4>{project.thematic}</h4>
                                <h2>{project.title}</h2>
                                <p>{project.subtitle}</p>
                                <SourceCodeLinks sourceCodeLinks={project.button.source_code}/>
                                <ProjectsBtn demo={project.button.demo} locale={locale}/>
                            </div>
                        </article>
                    ))}
                </section>

                <section className="tech" >
                  
                  <div className="tech__image"></div>

                  <div className="tech__content" id="technologies">
                    {
                      data.section3.tech.map((tech:any, index:number)=> (
                        <div key={index} className="tech__content--block">
                          <h2 className="tech__content--block__title">{tech.title}</h2>
                          <div className="tech__content--block__grid">
                          {
                            tech.images.map((photo:any, i:number)=> (
                              <div key={i}>
                                <Image 
                                  src={photo.image} 
                                  alt={photo.name} 
                                  layout="fill"
                                />
                              </div>
                            ))
                          }
                          </div>
                        </div>
                      ))
                    }
                  </div>
                </section>
            </main>
            <Footer />
        </>
    );
};

export default Home;

export async function getStaticProps(context:NextPageContext) {
  const data = context.locale === "es" ? HomeSpanish : HomeEnglish;
  return {
    props: {
      data,
      locale: context.locale
    }, 
  }
}
